# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RmoiZ7TrKMH6m0KW2ecSJYTwLhCPJvAi
"""

#1
import numpy as np
arr =  np.array([[[255,0,0]],[[127,127,127]]])
# 1,0 ,0
grey=0
for idx,one in enumerate(arr):
  while idx ==1:
    for two in one:
      for  idxx ,three in enumerate(two):
        while idxx ==0:
          grey = 0.2989 * arr[two][three] +0.5870*arr[two][three+1] +0.1140*arr[two][three+2]

print(grey)

#2
import numpy as np
persondata = np.array([[[165,80,30]]])

mean  = np.mean(persondata)
std = np.std(persondata)

#3
import numpy as np
sensordata = np.array([[[1,2,3]]])

sensor_up = sensordata.reshape(-1)
print(sensor_up)
sensor_final = sensor_up.reshape(2,-1)

#4
import numpy as np

player = np.array([[10,20,30],[30,20,40]])
length = len(player[0])
for idx1,val in enumerate(player):
    p_firstgame  = player[idx1][1]
    p_lastgame = player[idx][length-1]
    diff = p_lastgame -p_firstgame
    print(diff)

#5
import numpy as np

students = np.array([[10,20,30,10,50],[30,20,40,20,70]])

average_score  = np.mean(students,axis=1)
print(average_score)

#7
import pandas as pd
data ={"Name":["alice","bob","charlie","David","eve","Frank"],"Age":[25,30,35,40,45,50],
       "City":["NY","la","chi","hou","phoe","miami"],
       "Department":["hr","it","finance","marketing","sales","it"]}

emp = pd.DataFrame(data)
filter = emp[(emp["Age"]<45 ) &(emp["Department"]!="hr")]
filtered_emp = filter[["Name","City"]]
print(filtered_emp)

#8
import pandas as pd
data ={"Product":["apple","bannana","cherry","Dates","eberry","Flour","grapes"],
       "Category":["fruit","fruit","fruit","fruit","fruit","Bakery","fruit"],
       "Price":[1.20,0.50,3.00,2.50,4.00,1.50,2.00],
       "Promotion":["True","False","True","True","False","True","False"]}

fruit = pd.DataFrame(data)
avg = fruit[fruit["Category"] =="fruit" ].mean()
promo_fruit = fruit[(fruit["Price"]>avg)  &  (fruit["Promotion"]=="False") & (fruit["Category"]=="fruit")]
promo_fruit_prod = promo_fruit[["Product"]]
print(promo_fruit_prod)

#9
import pandas as pd
data ={"emp":["alice","bob","charlie","David","eve"],
    "Department":["Electronics","Electronics","clothing","clothing","homegoods"],

       "Manager":["a","b","c","d","e"]

}

data2 ={"emp":["alice","bob","charlie","David","eve"],
    "project":["p1","p2","po3","p4","p5"]
}

ds1 = pd.DataFrame(data)
ds2 = pd.DataFrame(data2)

final = pd.merge(left:ds1,rightL:ds2 on emp)

#10
import pandas as pd
data ={"Department":["Electronics","Electronics","clothing","clothing","homegoods"],
       "Salesperson":["alice","bob","charlie","David","eve"],
       "Sales":[70000,50000,30000,40000,60000]
}

sales  = pd.DataFrame(data)
salesresult = sales.groupby(["Department","Salesperson"]).agg(
    average_sales  = ("Sales","mean")
)

print(salesresult)